### ISSUE TITLE
Linux restoring and building solution on GitHub action using later package version is broken

### ISSUE THREAD

**Issue by DragosDanielBoia** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#29]
**Describe the bug**
Create an action with the script below, the build will break, if you include any version below [106.0.1370.34] will pass.

```
name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    tags:
      - 'v*'
jobs:
  build-and-publish-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x

    - name: Install dependencies
      run: dotnet restore {a sln containing <PackageReference Include="Selenium.WebDriver.MSEdgeDriver" Version="*" />} 
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - name: Build
      run: dotnet build {a sln containing <PackageReference Include="Selenium.WebDriver.MSEdgeDriver" Version="*" />} --configuration Release --no-restore
 ```
